version: "3"
services:
  node:
    image: sidechain/node
    tty: true
    stdin_open: true
    volumes:
      - ./data:/root/.sidechaind
    ports:
      - 26657:26657
      - 8545:8545
      - 1317:1317
      - 8546:8546
    command:
      - start
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --json-rpc.address=0.0.0.0:8545
      - --json-rpc.ws-address=0.0.0.0:8546
