##########################################
## Docker compose for local development ##
##########################################
version: "3.5"

services:
  node0:
    build:
      context: ../..
      dockerfile: development/deployment/Dockerfile-node0
    container_name: side_testnet_node0
    ports:
      - "26657:26657"
      - "9090:9090"
      - "1317:1317"

networks:
  default:
    name: side-network
